In [15]:
import pandas as pd
import numpy as np

In [16]:
icc = pd.read_csv("IccDiffData.csv")
icc

Team1             Team2  Rating1  Rating2  RatingDiff  Stand1  \
0     India IND        Turkey TUR      268        0         268    1000   
1     India IND      Thailand THA      268        0         268    1000   
2     India IND      Eswatini SWA      268        0         268    1000   
3     India IND       Lesotho LES      268        0         268    1000   
4     India IND       Estonia EST      268        0         268    1000   
...         ...               ...      ...      ...         ...     ...   
1880  Kenya KEN       Germany GER      104       84          20    1500   
1881  Kenya KEN       Bermuda BRM      104       88          16    1500   
1882  Kenya KEN  Saudi Arabia SDA      104       94          10    1500   
1883  Kenya KEN       Bahrain BRN      104       96           8    1500   
1884  Kenya KEN      Tanzania TAN      104       96           8    1500   

      Stand2  
0       1500  
1       1500  
2       1500  
3       1500  
4       1500  
...      ...  
1880    2100  
1881    2100  
1882    2100  
1883    2100  
1884    2100  

[1885 rows x 7 columns]

In [17]:

icc.head()

Team1         Team2  Rating1  Rating2  RatingDiff  Stand1  Stand2
0  India IND    Turkey TUR      268        0         268    1000    1500
1  India IND  Thailand THA      268        0         268    1000    1500
2  India IND  Eswatini SWA      268        0         268    1000    1500
3  India IND   Lesotho LES      268        0         268    1000    1500
4  India IND   Estonia EST      268        0         268    1000    1500

In [18]:
icc["Team1"].unique()

array(['India IND', 'England ENG', 'Pakistan PAK', 'South Africa SA',
       'New Zealand NZ', 'Australia AUS', 'West Indies WI',
       'Sri Lanka SL', 'Bangladesh BAN', 'Afghanistan AFG',
       'Zimbabwe ZIM', 'Ireland IRE', 'UAE UAE', 'Namibia NAM',
       'Scotland SCO', 'Nepal NEP', 'Oman OMA', 'Netherlands NED',
       'Papua New Guinea PNG', 'Hong Kong HK', 'Canada CAN', 'Jersey JSY',
       'Qatar QAT', 'Uganda UGA', 'Kuwait KUW', 'United States USA',
       'Singapore SIN', 'Malaysia MAS', 'Italy ITA', 'Kenya KEN'],
      dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
le_Team1 = LabelEncoder()
icc['Team1'] = le_Team1.fit_transform(icc['Team1'])
icc['Team1'].unique()



array([ 6,  4, 18, 23, 16,  1, 28, 24,  2,  0, 29,  7, 25, 13, 21, 14, 17,
       15, 19,  5,  3,  9, 20, 26, 11, 27, 22, 12,  8, 10])

In [20]:
icc["Team2"].unique()

array(['Turkey TUR', 'Thailand THA', 'Eswatini SWA', 'Lesotho LES',
       'Estonia EST', 'Gibraltar GIB', 'Greece GRE', 'Maldives MDV',
       'Seychelles SEY', 'Bulgaria BUL', 'Samoa SAM', 'Serbia SER',
       'Rwanda RWA', 'Panama PAN', 'Hungary HUN', 'Belize BIZ',
       'Mozambique MOZ', 'Bahamas BAH', 'Cyprus CYP', 'Bhutan BHU',
       'Sierra Leone SRL', 'Luxembourg LUX', 'Switzerland CHE',
       'Malta MLT', 'Czech Republic CZE', 'Ghana GHA', 'Sweden SWE',
       'Malawi MAW', 'Argentina ARG', 'Finland FIN', 'France FRA',
       'Norway NOR', 'Vanuatu VAN', 'Romania ROM', 'Portugal POR',
       'Botswana BOT', 'Nigeria NGR', 'Austria AUT', 'Cayman Islands CAY',
       'Belgium BEL', 'Isle of Man IOM', 'Guernsey GSY', 'Denmark DEN',
       'Spain ESP', 'Germany GER', 'Bermuda BRM', 'Tanzania TAN',
       'Saudi Arabia SDA', 'Bahrain BRN', 'Malaysia MAS', 'Italy ITA',
       'Kenya KEN', 'Singapore SIN', 'Uganda UGA', 'United States USA',
       'Kuwait KUW', 'Qatar QAT', 'Jerse

In [21]:
le_Team2 = LabelEncoder()
icc['Team2'] = le_Team2.fit_transform(icc['Team2'])
icc['Team2'].unique()

array([73, 72, 21, 38, 20, 27, 28, 42, 63, 12, 59, 62, 58, 53, 31,  8, 44,
        4, 16, 10, 64, 39, 70, 43, 17, 26, 69, 40,  1, 23, 24, 50, 77, 57,
       55, 11, 49,  3, 14,  7, 33, 29, 18, 67, 25,  9, 71, 60,  5, 41, 34,
       36, 65, 75, 76, 37, 56, 35, 13, 30, 54, 47, 51, 46, 61, 45, 74, 32,
       79,  0,  6, 68, 78,  2, 48, 66, 52, 19, 22, 15])

In [22]:
X= icc[['Team1','Team2' ,'Rating1','Rating2','RatingDiff']]
y=icc[['Stand1','Stand2']]

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.1)
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)

LinearRegression()

In [24]:
y_pred= linear_reg.predict(X_test)
y_pred

array([[1230.93508759, 1835.93369535],
       [ 946.53298403, 1434.43037738],
       [1150.43434629, 1707.89710634],
       [1065.17122075, 1608.22383987],
       [1336.47468978, 1978.26827563],
       [1045.96735124, 1576.05820503],
       [1045.50467947, 1580.52985264],
       [1107.30254028, 1667.78220249],
       [1492.02631891, 2186.8427218 ],
       [1006.65177678, 1512.89840349],
       [1339.301479  , 1978.43646071],
       [1055.80101959, 1591.42460574],
       [1268.00421183, 1874.2988763 ],
       [1180.13467675, 1767.91206008],
       [1371.13763587, 2022.52997676],
       [1168.20707308, 1747.82473087],
       [1268.8631319 , 1888.3481979 ],
       [1320.99296444, 1952.95802915],
       [1029.11588775, 1554.61510709],
       [ 971.45733043, 1467.39487667],
       [1503.35239762, 2190.08200617],
       [1183.54723468, 1757.3723674 ],
       [1168.33853509, 1747.72505058],
       [1126.40587881, 1687.92303628],
       [1046.76421839, 1575.42396308],
       [ 983.69891974, 14

In [25]:
linear_reg.score(X_test, y_test)

0.776553092069501

In [26]:
import pickle


In [30]:
data = {"model":linear_reg, "le_Team1": le_Team1, "le_Team2" : le_Team2 }
with open('cricket_pred.pkl','wb') as file:
    pickle.dump(data,file)

In [31]:
with open('cricket_pred.pkl','rb') as file:
    data= pickle.load(file)

model = data["model"]
le_Team1= data["le_Team1"]
le_Team2= data["le_Team2"]
    

In [33]:
y_pred = model.predict(X)
y_pred

array([[ 900.51286619, 1369.14111117],
       [ 900.71167646, 1369.36466247],
       [ 910.85100054, 1380.76577867],
       ...,
       [1345.41627405, 1992.91342548],
       [1362.71114201, 2013.89083555],
       [1349.5896638 , 1999.13644988]])